/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ApiregistrationV1beta1ServiceReference : ServiceReference holds a reference to Service.legacy.k8s.io



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiregistrationV1beta1ServiceReference {
    /// Name is the name of the service
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Namespace is the namespace of the service
    #[serde(rename = "namespace", skip_serializing_if = "Option::is_none")]
    pub namespace: Option<String>,
    /// If specified, the port on the service that hosting webhook. Default to 443 for backward compatibility. `port` should be a valid port number (1-65535, inclusive).
    #[serde(rename = "port", skip_serializing_if = "Option::is_none")]
    pub port: Option<i32>,
}

impl ApiregistrationV1beta1ServiceReference {
    /// ServiceReference holds a reference to Service.legacy.k8s.io
    pub fn new() -> ApiregistrationV1beta1ServiceReference {
        ApiregistrationV1beta1ServiceReference {
            name: None,
            namespace: None,
            port: None,
        }
    }
}


