/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1ContainerStateRunning : ContainerStateRunning is a running state of a container.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1ContainerStateRunning {
    /// Time at which the container was last (re-)started
    #[serde(rename = "startedAt", skip_serializing_if = "Option::is_none")]
    pub started_at: Option<String>,
}

impl V1ContainerStateRunning {
    /// ContainerStateRunning is a running state of a container.
    pub fn new() -> V1ContainerStateRunning {
        V1ContainerStateRunning {
            started_at: None,
        }
    }
}


