/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1ContainerState : ContainerState holds a possible state of container. Only one of its members may be specified. If none of them is specified, the default one is ContainerStateWaiting.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1ContainerState {
    #[serde(rename = "running", skip_serializing_if = "Option::is_none")]
    pub running: Option<crate::models::V1ContainerStateRunning>,
    #[serde(rename = "terminated", skip_serializing_if = "Option::is_none")]
    pub terminated: Option<crate::models::V1ContainerStateTerminated>,
    #[serde(rename = "waiting", skip_serializing_if = "Option::is_none")]
    pub waiting: Option<crate::models::V1ContainerStateWaiting>,
}

impl V1ContainerState {
    /// ContainerState holds a possible state of container. Only one of its members may be specified. If none of them is specified, the default one is ContainerStateWaiting.
    pub fn new() -> V1ContainerState {
        V1ContainerState {
            running: None,
            terminated: None,
            waiting: None,
        }
    }
}


