/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1EphemeralContainers : A list of ephemeral containers used with the Pod ephemeralcontainers subresource.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1EphemeralContainers {
    /// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    #[serde(rename = "apiVersion", skip_serializing_if = "Option::is_none")]
    pub api_version: Option<String>,
    /// A list of ephemeral containers associated with this pod. New ephemeral containers may be appended to this list, but existing ephemeral containers may not be removed or modified.
    #[serde(rename = "ephemeralContainers")]
    pub ephemeral_containers: Vec<crate::models::V1EphemeralContainer>,
    /// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    #[serde(rename = "kind", skip_serializing_if = "Option::is_none")]
    pub kind: Option<String>,
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<Box<crate::models::V1ObjectMeta>>,
}

impl V1EphemeralContainers {
    /// A list of ephemeral containers used with the Pod ephemeralcontainers subresource.
    pub fn new(ephemeral_containers: Vec<crate::models::V1EphemeralContainer>) -> V1EphemeralContainers {
        V1EphemeralContainers {
            api_version: None,
            ephemeral_containers,
            kind: None,
            metadata: None,
        }
    }
}


