/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1EnvFromSource : EnvFromSource represents the source of a set of ConfigMaps



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1EnvFromSource {
    #[serde(rename = "configMapRef", skip_serializing_if = "Option::is_none")]
    pub config_map_ref: Option<crate::models::V1ConfigMapEnvSource>,
    /// An optional identifier to prepend to each key in the ConfigMap. Must be a C_IDENTIFIER.
    #[serde(rename = "prefix", skip_serializing_if = "Option::is_none")]
    pub prefix: Option<String>,
    #[serde(rename = "secretRef", skip_serializing_if = "Option::is_none")]
    pub secret_ref: Option<crate::models::V1SecretEnvSource>,
}

impl V1EnvFromSource {
    /// EnvFromSource represents the source of a set of ConfigMaps
    pub fn new() -> V1EnvFromSource {
        V1EnvFromSource {
            config_map_ref: None,
            prefix: None,
            secret_ref: None,
        }
    }
}


