/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1JobCondition : JobCondition describes current state of a job.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1JobCondition {
    /// Last time the condition was checked.
    #[serde(rename = "lastProbeTime", skip_serializing_if = "Option::is_none")]
    pub last_probe_time: Option<String>,
    /// Last time the condition transit from one status to another.
    #[serde(rename = "lastTransitionTime", skip_serializing_if = "Option::is_none")]
    pub last_transition_time: Option<String>,
    /// Human readable message indicating details about last transition.
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    /// (brief) reason for the condition's last transition.
    #[serde(rename = "reason", skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    /// Status of the condition, one of True, False, Unknown.
    #[serde(rename = "status")]
    pub status: String,
    /// Type of job condition, Complete or Failed.
    #[serde(rename = "type")]
    pub _type: String,
}

impl V1JobCondition {
    /// JobCondition describes current state of a job.
    pub fn new(status: String, _type: String) -> V1JobCondition {
        V1JobCondition {
            last_probe_time: None,
            last_transition_time: None,
            message: None,
            reason: None,
            status,
            _type,
        }
    }
}


