/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1LoadBalancerStatus : LoadBalancerStatus represents the status of a load-balancer.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1LoadBalancerStatus {
    /// Ingress is a list containing ingress points for the load-balancer. Traffic intended for the service should be sent to these ingress points.
    #[serde(rename = "ingress", skip_serializing_if = "Option::is_none")]
    pub ingress: Option<Vec<crate::models::V1LoadBalancerIngress>>,
}

impl V1LoadBalancerStatus {
    /// LoadBalancerStatus represents the status of a load-balancer.
    pub fn new() -> V1LoadBalancerStatus {
        V1LoadBalancerStatus {
            ingress: None,
        }
    }
}


