/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1NodeSelectorTerm : A null or empty node selector term matches no objects. The requirements of them are ANDed. The TopologySelectorTerm type implements a subset of the NodeSelectorTerm.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1NodeSelectorTerm {
    /// A list of node selector requirements by node's labels.
    #[serde(rename = "matchExpressions", skip_serializing_if = "Option::is_none")]
    pub match_expressions: Option<Vec<crate::models::V1NodeSelectorRequirement>>,
    /// A list of node selector requirements by node's fields.
    #[serde(rename = "matchFields", skip_serializing_if = "Option::is_none")]
    pub match_fields: Option<Vec<crate::models::V1NodeSelectorRequirement>>,
}

impl V1NodeSelectorTerm {
    /// A null or empty node selector term matches no objects. The requirements of them are ANDed. The TopologySelectorTerm type implements a subset of the NodeSelectorTerm.
    pub fn new() -> V1NodeSelectorTerm {
        V1NodeSelectorTerm {
            match_expressions: None,
            match_fields: None,
        }
    }
}


