/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1PersistentVolumeList : PersistentVolumeList is a list of PersistentVolume items.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1PersistentVolumeList {
    /// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    #[serde(rename = "apiVersion", skip_serializing_if = "Option::is_none")]
    pub api_version: Option<String>,
    /// List of persistent volumes. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes
    #[serde(rename = "items")]
    pub items: Vec<crate::models::V1PersistentVolume>,
    /// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    #[serde(rename = "kind", skip_serializing_if = "Option::is_none")]
    pub kind: Option<String>,
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<crate::models::V1ListMeta>,
}

impl V1PersistentVolumeList {
    /// PersistentVolumeList is a list of PersistentVolume items.
    pub fn new(items: Vec<crate::models::V1PersistentVolume>) -> V1PersistentVolumeList {
        V1PersistentVolumeList {
            api_version: None,
            items,
            kind: None,
            metadata: None,
        }
    }
}


