/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1PodDnsConfigOption : PodDNSConfigOption defines DNS resolver options of a pod.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1PodDnsConfigOption {
    /// Required.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

impl V1PodDnsConfigOption {
    /// PodDNSConfigOption defines DNS resolver options of a pod.
    pub fn new() -> V1PodDnsConfigOption {
        V1PodDnsConfigOption {
            name: None,
            value: None,
        }
    }
}


