/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1ScopedResourceSelectorRequirement : A scoped-resource selector requirement is a selector that contains values, a scope name, and an operator that relates the scope name and values.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1ScopedResourceSelectorRequirement {
    /// Represents a scope's relationship to a set of values. Valid operators are In, NotIn, Exists, DoesNotExist.
    #[serde(rename = "operator")]
    pub operator: String,
    /// The name of the scope that the selector applies to.
    #[serde(rename = "scopeName")]
    pub scope_name: String,
    /// An array of string values. If the operator is In or NotIn, the values array must be non-empty. If the operator is Exists or DoesNotExist, the values array must be empty. This array is replaced during a strategic merge patch.
    #[serde(rename = "values", skip_serializing_if = "Option::is_none")]
    pub values: Option<Vec<String>>,
}

impl V1ScopedResourceSelectorRequirement {
    /// A scoped-resource selector requirement is a selector that contains values, a scope name, and an operator that relates the scope name and values.
    pub fn new(operator: String, scope_name: String) -> V1ScopedResourceSelectorRequirement {
        V1ScopedResourceSelectorRequirement {
            operator,
            scope_name,
            values: None,
        }
    }
}


