/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1TokenReviewSpec : TokenReviewSpec is a description of the token authentication request.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1TokenReviewSpec {
    /// Audiences is a list of the identifiers that the resource server presented with the token identifies as. Audience-aware token authenticators will verify that the token was intended for at least one of the audiences in this list. If no audiences are provided, the audience will default to the audience of the Kubernetes apiserver.
    #[serde(rename = "audiences", skip_serializing_if = "Option::is_none")]
    pub audiences: Option<Vec<String>>,
    /// Token is the opaque bearer token.
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
}

impl V1TokenReviewSpec {
    /// TokenReviewSpec is a description of the token authentication request.
    pub fn new() -> V1TokenReviewSpec {
        V1TokenReviewSpec {
            audiences: None,
            token: None,
        }
    }
}


