/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1VolumeProjection : Projection that may be projected along with other supported volume types



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1VolumeProjection {
    #[serde(rename = "configMap", skip_serializing_if = "Option::is_none")]
    pub config_map: Option<crate::models::V1ConfigMapProjection>,
    #[serde(rename = "downwardAPI", skip_serializing_if = "Option::is_none")]
    pub downward_api: Option<crate::models::V1DownwardApiProjection>,
    #[serde(rename = "secret", skip_serializing_if = "Option::is_none")]
    pub secret: Option<crate::models::V1SecretProjection>,
    #[serde(rename = "serviceAccountToken", skip_serializing_if = "Option::is_none")]
    pub service_account_token: Option<crate::models::V1ServiceAccountTokenProjection>,
}

impl V1VolumeProjection {
    /// Projection that may be projected along with other supported volume types
    pub fn new() -> V1VolumeProjection {
        V1VolumeProjection {
            config_map: None,
            downward_api: None,
            secret: None,
            service_account_token: None,
        }
    }
}


