/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1WindowsSecurityContextOptions : WindowsSecurityContextOptions contain Windows-specific options and credentials.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1WindowsSecurityContextOptions {
    /// GMSACredentialSpec is where the GMSA admission webhook (https://github.com/kubernetes-sigs/windows-gmsa) inlines the contents of the GMSA credential spec named by the GMSACredentialSpecName field.
    #[serde(rename = "gmsaCredentialSpec", skip_serializing_if = "Option::is_none")]
    pub gmsa_credential_spec: Option<String>,
    /// GMSACredentialSpecName is the name of the GMSA credential spec to use.
    #[serde(rename = "gmsaCredentialSpecName", skip_serializing_if = "Option::is_none")]
    pub gmsa_credential_spec_name: Option<String>,
    /// The UserName in Windows to run the entrypoint of the container process. Defaults to the user specified in image metadata if unspecified. May also be set in PodSecurityContext. If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence.
    #[serde(rename = "runAsUserName", skip_serializing_if = "Option::is_none")]
    pub run_as_user_name: Option<String>,
}

impl V1WindowsSecurityContextOptions {
    /// WindowsSecurityContextOptions contain Windows-specific options and credentials.
    pub fn new() -> V1WindowsSecurityContextOptions {
        V1WindowsSecurityContextOptions {
            gmsa_credential_spec: None,
            gmsa_credential_spec_name: None,
            run_as_user_name: None,
        }
    }
}


