/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1beta1VolumeAttachmentSource : VolumeAttachmentSource represents a volume that should be attached. Right now only PersistenVolumes can be attached via external attacher, in future we may allow also inline volumes in pods. Exactly one member can be set.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1beta1VolumeAttachmentSource {
    #[serde(rename = "inlineVolumeSpec", skip_serializing_if = "Option::is_none")]
    pub inline_volume_spec: Option<Box<crate::models::V1PersistentVolumeSpec>>,
    /// Name of the persistent volume to attach.
    #[serde(rename = "persistentVolumeName", skip_serializing_if = "Option::is_none")]
    pub persistent_volume_name: Option<String>,
}

impl V1beta1VolumeAttachmentSource {
    /// VolumeAttachmentSource represents a volume that should be attached. Right now only PersistenVolumes can be attached via external attacher, in future we may allow also inline volumes in pods. Exactly one member can be set.
    pub fn new() -> V1beta1VolumeAttachmentSource {
        V1beta1VolumeAttachmentSource {
            inline_volume_spec: None,
            persistent_volume_name: None,
        }
    }
}


