/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1beta1EndpointHints : EndpointHints provides hints describing how an endpoint should be consumed.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1beta1EndpointHints {
    /// forZones indicates the zone(s) this endpoint should be consumed by to enable topology aware routing. May contain a maximum of 8 entries.
    #[serde(rename = "forZones", skip_serializing_if = "Option::is_none")]
    pub for_zones: Option<Vec<crate::models::V1beta1ForZone>>,
}

impl V1beta1EndpointHints {
    /// EndpointHints provides hints describing how an endpoint should be consumed.
    pub fn new() -> V1beta1EndpointHints {
        V1beta1EndpointHints {
            for_zones: None,
        }
    }
}


