/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1beta1ExternalDocumentation : ExternalDocumentation allows referencing an external resource for extended documentation.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1beta1ExternalDocumentation {
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl V1beta1ExternalDocumentation {
    /// ExternalDocumentation allows referencing an external resource for extended documentation.
    pub fn new() -> V1beta1ExternalDocumentation {
        V1beta1ExternalDocumentation {
            description: None,
            url: None,
        }
    }
}


