/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1beta1PodSecurityPolicySpec : PodSecurityPolicySpec defines the policy enforced.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1beta1PodSecurityPolicySpec {
    /// allowPrivilegeEscalation determines if a pod can request to allow privilege escalation. If unspecified, defaults to true.
    #[serde(rename = "allowPrivilegeEscalation", skip_serializing_if = "Option::is_none")]
    pub allow_privilege_escalation: Option<bool>,
    /// AllowedCSIDrivers is an allowlist of inline CSI drivers that must be explicitly set to be embedded within a pod spec. An empty value indicates that any CSI driver can be used for inline ephemeral volumes. This is a beta field, and is only honored if the API server enables the CSIInlineVolume feature gate.
    #[serde(rename = "allowedCSIDrivers", skip_serializing_if = "Option::is_none")]
    pub allowed_csi_drivers: Option<Vec<crate::models::V1beta1AllowedCsiDriver>>,
    /// allowedCapabilities is a list of capabilities that can be requested to add to the container. Capabilities in this field may be added at the pod author's discretion. You must not list a capability in both allowedCapabilities and requiredDropCapabilities.
    #[serde(rename = "allowedCapabilities", skip_serializing_if = "Option::is_none")]
    pub allowed_capabilities: Option<Vec<String>>,
    /// allowedFlexVolumes is an allowlist of Flexvolumes.  Empty or nil indicates that all Flexvolumes may be used.  This parameter is effective only when the usage of the Flexvolumes is allowed in the \"volumes\" field.
    #[serde(rename = "allowedFlexVolumes", skip_serializing_if = "Option::is_none")]
    pub allowed_flex_volumes: Option<Vec<crate::models::V1beta1AllowedFlexVolume>>,
    /// allowedHostPaths is an allowlist of host paths. Empty indicates that all host paths may be used.
    #[serde(rename = "allowedHostPaths", skip_serializing_if = "Option::is_none")]
    pub allowed_host_paths: Option<Vec<crate::models::V1beta1AllowedHostPath>>,
    /// AllowedProcMountTypes is an allowlist of allowed ProcMountTypes. Empty or nil indicates that only the DefaultProcMountType may be used. This requires the ProcMountType feature flag to be enabled.
    #[serde(rename = "allowedProcMountTypes", skip_serializing_if = "Option::is_none")]
    pub allowed_proc_mount_types: Option<Vec<String>>,
    /// allowedUnsafeSysctls is a list of explicitly allowed unsafe sysctls, defaults to none. Each entry is either a plain sysctl name or ends in \"*\" in which case it is considered as a prefix of allowed sysctls. Single * means all unsafe sysctls are allowed. Kubelet has to allowlist all allowed unsafe sysctls explicitly to avoid rejection.  Examples: e.g. \"foo/_*\" allows \"foo/bar\", \"foo/baz\", etc. e.g. \"foo.*\" allows \"foo.bar\", \"foo.baz\", etc.
    #[serde(rename = "allowedUnsafeSysctls", skip_serializing_if = "Option::is_none")]
    pub allowed_unsafe_sysctls: Option<Vec<String>>,
    /// defaultAddCapabilities is the default set of capabilities that will be added to the container unless the pod spec specifically drops the capability.  You may not list a capability in both defaultAddCapabilities and requiredDropCapabilities. Capabilities added here are implicitly allowed, and need not be included in the allowedCapabilities list.
    #[serde(rename = "defaultAddCapabilities", skip_serializing_if = "Option::is_none")]
    pub default_add_capabilities: Option<Vec<String>>,
    /// defaultAllowPrivilegeEscalation controls the default setting for whether a process can gain more privileges than its parent process.
    #[serde(rename = "defaultAllowPrivilegeEscalation", skip_serializing_if = "Option::is_none")]
    pub default_allow_privilege_escalation: Option<bool>,
    /// forbiddenSysctls is a list of explicitly forbidden sysctls, defaults to none. Each entry is either a plain sysctl name or ends in \"*\" in which case it is considered as a prefix of forbidden sysctls. Single * means all sysctls are forbidden.  Examples: e.g. \"foo/_*\" forbids \"foo/bar\", \"foo/baz\", etc. e.g. \"foo.*\" forbids \"foo.bar\", \"foo.baz\", etc.
    #[serde(rename = "forbiddenSysctls", skip_serializing_if = "Option::is_none")]
    pub forbidden_sysctls: Option<Vec<String>>,
    #[serde(rename = "fsGroup")]
    pub fs_group: Box<crate::models::V1beta1FsGroupStrategyOptions>,
    /// hostIPC determines if the policy allows the use of HostIPC in the pod spec.
    #[serde(rename = "hostIPC", skip_serializing_if = "Option::is_none")]
    pub host_ipc: Option<bool>,
    /// hostNetwork determines if the policy allows the use of HostNetwork in the pod spec.
    #[serde(rename = "hostNetwork", skip_serializing_if = "Option::is_none")]
    pub host_network: Option<bool>,
    /// hostPID determines if the policy allows the use of HostPID in the pod spec.
    #[serde(rename = "hostPID", skip_serializing_if = "Option::is_none")]
    pub host_pid: Option<bool>,
    /// hostPorts determines which host port ranges are allowed to be exposed.
    #[serde(rename = "hostPorts", skip_serializing_if = "Option::is_none")]
    pub host_ports: Option<Vec<crate::models::V1beta1HostPortRange>>,
    /// privileged determines if a pod can request to be run as privileged.
    #[serde(rename = "privileged", skip_serializing_if = "Option::is_none")]
    pub privileged: Option<bool>,
    /// readOnlyRootFilesystem when set to true will force containers to run with a read only root file system.  If the container specifically requests to run with a non-read only root file system the PSP should deny the pod. If set to false the container may run with a read only root file system if it wishes but it will not be forced to.
    #[serde(rename = "readOnlyRootFilesystem", skip_serializing_if = "Option::is_none")]
    pub read_only_root_filesystem: Option<bool>,
    /// requiredDropCapabilities are the capabilities that will be dropped from the container.  These are required to be dropped and cannot be added.
    #[serde(rename = "requiredDropCapabilities", skip_serializing_if = "Option::is_none")]
    pub required_drop_capabilities: Option<Vec<String>>,
    #[serde(rename = "runAsGroup", skip_serializing_if = "Option::is_none")]
    pub run_as_group: Option<Box<crate::models::V1beta1RunAsGroupStrategyOptions>>,
    #[serde(rename = "runAsUser")]
    pub run_as_user: Box<crate::models::V1beta1RunAsUserStrategyOptions>,
    #[serde(rename = "runtimeClass", skip_serializing_if = "Option::is_none")]
    pub runtime_class: Option<Box<crate::models::V1beta1RuntimeClassStrategyOptions>>,
    #[serde(rename = "seLinux")]
    pub se_linux: Box<crate::models::V1beta1SeLinuxStrategyOptions>,
    #[serde(rename = "supplementalGroups")]
    pub supplemental_groups: Box<crate::models::V1beta1SupplementalGroupsStrategyOptions>,
    /// volumes is an allowlist of volume plugins. Empty indicates that no volumes may be used. To allow all volumes you may use '*'.
    #[serde(rename = "volumes", skip_serializing_if = "Option::is_none")]
    pub volumes: Option<Vec<String>>,
}

impl V1beta1PodSecurityPolicySpec {
    /// PodSecurityPolicySpec defines the policy enforced.
    pub fn new(fs_group: crate::models::V1beta1FsGroupStrategyOptions, run_as_user: crate::models::V1beta1RunAsUserStrategyOptions, se_linux: crate::models::V1beta1SeLinuxStrategyOptions, supplemental_groups: crate::models::V1beta1SupplementalGroupsStrategyOptions) -> V1beta1PodSecurityPolicySpec {
        V1beta1PodSecurityPolicySpec {
            allow_privilege_escalation: None,
            allowed_csi_drivers: None,
            allowed_capabilities: None,
            allowed_flex_volumes: None,
            allowed_host_paths: None,
            allowed_proc_mount_types: None,
            allowed_unsafe_sysctls: None,
            default_add_capabilities: None,
            default_allow_privilege_escalation: None,
            forbidden_sysctls: None,
            fs_group: Box::new(fs_group),
            host_ipc: None,
            host_network: None,
            host_pid: None,
            host_ports: None,
            privileged: None,
            read_only_root_filesystem: None,
            required_drop_capabilities: None,
            run_as_group: None,
            run_as_user: Box::new(run_as_user),
            runtime_class: None,
            se_linux: Box::new(se_linux),
            supplemental_groups: Box::new(supplemental_groups),
            volumes: None,
        }
    }
}


