/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1beta1LimitResponse : LimitResponse defines how to handle requests that can not be executed right now.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1beta1LimitResponse {
    #[serde(rename = "queuing", skip_serializing_if = "Option::is_none")]
    pub queuing: Option<Box<crate::models::V1beta1QueuingConfiguration>>,
    /// `type` is \"Queue\" or \"Reject\". \"Queue\" means that requests that can not be executed upon arrival are held in a queue until they can be executed or a queuing limit is reached. \"Reject\" means that requests that can not be executed upon arrival are rejected. Required.
    #[serde(rename = "type")]
    pub _type: String,
}

impl V1beta1LimitResponse {
    /// LimitResponse defines how to handle requests that can not be executed right now.
    pub fn new(_type: String) -> V1beta1LimitResponse {
        V1beta1LimitResponse {
            queuing: None,
            _type,
        }
    }
}


