/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1beta1FlowDistinguisherMethod : FlowDistinguisherMethod specifies the method of a flow distinguisher.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1beta1FlowDistinguisherMethod {
    /// `type` is the type of flow distinguisher method The supported types are \"ByUser\" and \"ByNamespace\". Required.
    #[serde(rename = "type")]
    pub _type: String,
}

impl V1beta1FlowDistinguisherMethod {
    /// FlowDistinguisherMethod specifies the method of a flow distinguisher.
    pub fn new(_type: String) -> V1beta1FlowDistinguisherMethod {
        V1beta1FlowDistinguisherMethod {
            _type,
        }
    }
}


