/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V2beta1MetricStatus : MetricStatus describes the last-read state of a single metric.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V2beta1MetricStatus {
    #[serde(rename = "containerResource", skip_serializing_if = "Option::is_none")]
    pub container_resource: Option<crate::models::V2beta1ContainerResourceMetricStatus>,
    #[serde(rename = "external", skip_serializing_if = "Option::is_none")]
    pub external: Option<crate::models::V2beta1ExternalMetricStatus>,
    #[serde(rename = "object", skip_serializing_if = "Option::is_none")]
    pub object: Option<crate::models::V2beta1ObjectMetricStatus>,
    #[serde(rename = "pods", skip_serializing_if = "Option::is_none")]
    pub pods: Option<crate::models::V2beta1PodsMetricStatus>,
    #[serde(rename = "resource", skip_serializing_if = "Option::is_none")]
    pub resource: Option<crate::models::V2beta1ResourceMetricStatus>,
    /// type is the type of metric source.  It will be one of \"ContainerResource\", \"External\", \"Object\", \"Pods\" or \"Resource\", each corresponds to a matching field in the object. Note: \"ContainerResource\" type is available on when the feature-gate HPAContainerMetrics is enabled
    #[serde(rename = "type")]
    pub _type: String,
}

impl V2beta1MetricStatus {
    /// MetricStatus describes the last-read state of a single metric.
    pub fn new(_type: String) -> V2beta1MetricStatus {
        V2beta1MetricStatus {
            container_resource: None,
            external: None,
            object: None,
            pods: None,
            resource: None,
            _type,
        }
    }
}


