/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use std::rc::Rc;
use std::borrow::Borrow;
#[allow(unused_imports)]
use std::option::Option;

use hyper;
use serde_json;
use futures::Future;

use super::{Error, configuration};
use super::request as __internal_request;

pub struct AuthorizationV1beta1ApiClient<C: hyper::client::Connect> {
    configuration: Rc<configuration::Configuration<C>>,
}

impl<C: hyper::client::Connect> AuthorizationV1beta1ApiClient<C> {
    pub fn new(configuration: Rc<configuration::Configuration<C>>) -> AuthorizationV1beta1ApiClient<C> {
        AuthorizationV1beta1ApiClient {
            configuration,
        }
    }
}

pub trait AuthorizationV1beta1Api {
    fn create_namespaced_local_subject_access_review(&self, namespace: &str, body: crate::models::V1beta1LocalSubjectAccessReview, dry_run: Option<&str>, field_manager: Option<&str>, pretty: Option<&str>) -> Box<dyn Future<Item = crate::models::V1beta1LocalSubjectAccessReview, Error = Error<serde_json::Value>>>;
    fn create_self_subject_access_review(&self, body: crate::models::V1beta1SelfSubjectAccessReview, dry_run: Option<&str>, field_manager: Option<&str>, pretty: Option<&str>) -> Box<dyn Future<Item = crate::models::V1beta1SelfSubjectAccessReview, Error = Error<serde_json::Value>>>;
    fn create_self_subject_rules_review(&self, body: crate::models::V1beta1SelfSubjectRulesReview, dry_run: Option<&str>, field_manager: Option<&str>, pretty: Option<&str>) -> Box<dyn Future<Item = crate::models::V1beta1SelfSubjectRulesReview, Error = Error<serde_json::Value>>>;
    fn create_subject_access_review(&self, body: crate::models::V1beta1SubjectAccessReview, dry_run: Option<&str>, field_manager: Option<&str>, pretty: Option<&str>) -> Box<dyn Future<Item = crate::models::V1beta1SubjectAccessReview, Error = Error<serde_json::Value>>>;
    fn get_api_resources(&self, ) -> Box<dyn Future<Item = crate::models::V1ApiResourceList, Error = Error<serde_json::Value>>>;
}

impl<C: hyper::client::Connect>AuthorizationV1beta1Api for AuthorizationV1beta1ApiClient<C> {
    fn create_namespaced_local_subject_access_review(&self, namespace: &str, body: crate::models::V1beta1LocalSubjectAccessReview, dry_run: Option<&str>, field_manager: Option<&str>, pretty: Option<&str>) -> Box<dyn Future<Item = crate::models::V1beta1LocalSubjectAccessReview, Error = Error<serde_json::Value>>> {
        let mut req = __internal_request::Request::new(hyper::Method::Post, "/apis/authorization.k8s.io/v1beta1/namespaces/{namespace}/localsubjectaccessreviews".to_string())
            .with_auth(__internal_request::Auth::ApiKey(__internal_request::ApiKey{
                in_header: true,
                in_query: false,
                param_name: "authorization".to_owned(),
            }))
        ;
        if let Some(ref s) = dry_run {
            req = req.with_query_param("dryRun".to_string(), s.to_string());
        }
        if let Some(ref s) = field_manager {
            req = req.with_query_param("fieldManager".to_string(), s.to_string());
        }
        if let Some(ref s) = pretty {
            req = req.with_query_param("pretty".to_string(), s.to_string());
        }
        req = req.with_path_param("namespace".to_string(), namespace.to_string());
        req = req.with_body_param(body);

        req.execute(self.configuration.borrow())
    }

    fn create_self_subject_access_review(&self, body: crate::models::V1beta1SelfSubjectAccessReview, dry_run: Option<&str>, field_manager: Option<&str>, pretty: Option<&str>) -> Box<dyn Future<Item = crate::models::V1beta1SelfSubjectAccessReview, Error = Error<serde_json::Value>>> {
        let mut req = __internal_request::Request::new(hyper::Method::Post, "/apis/authorization.k8s.io/v1beta1/selfsubjectaccessreviews".to_string())
            .with_auth(__internal_request::Auth::ApiKey(__internal_request::ApiKey{
                in_header: true,
                in_query: false,
                param_name: "authorization".to_owned(),
            }))
        ;
        if let Some(ref s) = dry_run {
            req = req.with_query_param("dryRun".to_string(), s.to_string());
        }
        if let Some(ref s) = field_manager {
            req = req.with_query_param("fieldManager".to_string(), s.to_string());
        }
        if let Some(ref s) = pretty {
            req = req.with_query_param("pretty".to_string(), s.to_string());
        }
        req = req.with_body_param(body);

        req.execute(self.configuration.borrow())
    }

    fn create_self_subject_rules_review(&self, body: crate::models::V1beta1SelfSubjectRulesReview, dry_run: Option<&str>, field_manager: Option<&str>, pretty: Option<&str>) -> Box<dyn Future<Item = crate::models::V1beta1SelfSubjectRulesReview, Error = Error<serde_json::Value>>> {
        let mut req = __internal_request::Request::new(hyper::Method::Post, "/apis/authorization.k8s.io/v1beta1/selfsubjectrulesreviews".to_string())
            .with_auth(__internal_request::Auth::ApiKey(__internal_request::ApiKey{
                in_header: true,
                in_query: false,
                param_name: "authorization".to_owned(),
            }))
        ;
        if let Some(ref s) = dry_run {
            req = req.with_query_param("dryRun".to_string(), s.to_string());
        }
        if let Some(ref s) = field_manager {
            req = req.with_query_param("fieldManager".to_string(), s.to_string());
        }
        if let Some(ref s) = pretty {
            req = req.with_query_param("pretty".to_string(), s.to_string());
        }
        req = req.with_body_param(body);

        req.execute(self.configuration.borrow())
    }

    fn create_subject_access_review(&self, body: crate::models::V1beta1SubjectAccessReview, dry_run: Option<&str>, field_manager: Option<&str>, pretty: Option<&str>) -> Box<dyn Future<Item = crate::models::V1beta1SubjectAccessReview, Error = Error<serde_json::Value>>> {
        let mut req = __internal_request::Request::new(hyper::Method::Post, "/apis/authorization.k8s.io/v1beta1/subjectaccessreviews".to_string())
            .with_auth(__internal_request::Auth::ApiKey(__internal_request::ApiKey{
                in_header: true,
                in_query: false,
                param_name: "authorization".to_owned(),
            }))
        ;
        if let Some(ref s) = dry_run {
            req = req.with_query_param("dryRun".to_string(), s.to_string());
        }
        if let Some(ref s) = field_manager {
            req = req.with_query_param("fieldManager".to_string(), s.to_string());
        }
        if let Some(ref s) = pretty {
            req = req.with_query_param("pretty".to_string(), s.to_string());
        }
        req = req.with_body_param(body);

        req.execute(self.configuration.borrow())
    }

    fn get_api_resources(&self, ) -> Box<dyn Future<Item = crate::models::V1ApiResourceList, Error = Error<serde_json::Value>>> {
        let mut req = __internal_request::Request::new(hyper::Method::Get, "/apis/authorization.k8s.io/v1beta1/".to_string())
            .with_auth(__internal_request::Auth::ApiKey(__internal_request::ApiKey{
                in_header: true,
                in_query: false,
                param_name: "authorization".to_owned(),
            }))
        ;

        req.execute(self.configuration.borrow())
    }

}
