/*
 * Kubernetes
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use std::rc::Rc;
use std::borrow::Borrow;
#[allow(unused_imports)]
use std::option::Option;

use hyper;
use serde_json;
use futures::Future;

use super::{Error, configuration};
use super::request as __internal_request;

pub struct DiscoveryApiClient<C: hyper::client::Connect> {
    configuration: Rc<configuration::Configuration<C>>,
}

impl<C: hyper::client::Connect> DiscoveryApiClient<C> {
    pub fn new(configuration: Rc<configuration::Configuration<C>>) -> DiscoveryApiClient<C> {
        DiscoveryApiClient {
            configuration,
        }
    }
}

pub trait DiscoveryApi {
    fn get_api_group(&self, ) -> Box<dyn Future<Item = crate::models::V1ApiGroup, Error = Error<serde_json::Value>>>;
}

impl<C: hyper::client::Connect>DiscoveryApi for DiscoveryApiClient<C> {
    fn get_api_group(&self, ) -> Box<dyn Future<Item = crate::models::V1ApiGroup, Error = Error<serde_json::Value>>> {
        let mut req = __internal_request::Request::new(hyper::Method::Get, "/apis/discovery.k8s.io/".to_string())
            .with_auth(__internal_request::Auth::ApiKey(__internal_request::ApiKey{
                in_header: true,
                in_query: false,
                param_name: "authorization".to_owned(),
            }))
        ;

        req.execute(self.configuration.borrow())
    }

}
